name: Generate Metrics

on:
  schedule:
    # run every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - main
    - master
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Create dist directory
        run: mkdir -p dist
        
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: Generate github-readme-streak-stats.svg
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&theme=transparent&hide_border=true&ring=8b5cf6&fire=8b5cf6&currStreakLabel=8b5cf6
          path: dist/streak-stats.svg
          
      - name: Generate github-readme-activity-graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: ${{ github.repository_owner }}
          options: theme=transparent&hide_border=true&color=8b5cf6&line=8b5cf6&point=ffffff
          output_path: dist/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate github-metrics (Activity)
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-activity.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: activity
          committer_branch: output
          config_timezone: Asia/Colombo
          
      - name: Generate github-metrics (Languages)
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          committer_branch: output
